Repository AY2324S1-CS2103T-F11-4/tp, pull requests merged in 2023-10, with the labels that each got.

#29 Client basic commands
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/MeowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/MeowCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Details.java
  src/main/java/seedu/address/model/person/Income.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Profession.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#45 Fix new interactions not being added to `Person`
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug

#76 Dashboard Command
  src/main/java/seedu/address/logic/commands/DashboardCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DashboardCommandParser.java
  src/main/java/seedu/address/model/person/Interaction.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Enhancement, priority.High

#94 Saving interactions to JSON
  .gitignore
  src/main/java/seedu/address/logic/commands/DashboardCommand.java
  src/main/java/seedu/address/logic/commands/InteractionCommand.java
  src/main/java/seedu/address/logic/parser/InteractionCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/interaction/Interaction.java
  src/main/java/seedu/address/model/person/interaction/InteractionList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInteraction.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/ClientProfilePanel.java
  src/main/java/seedu/address/ui/InteractionEntry.java
  src/test/java/seedu/address/logic/commands/InteractionCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#95 Ported Dashboard Logic
  src/main/java/seedu/address/logic/commands/DashboardCommand.java
  src/main/java/seedu/address/model/Dashboard.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
Labels: priority.High
