Repository AY2324S1-CS2103T-F11-4/tp, pull requests merged in 2023-11, with the labels that each got.

#112 Reminders
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InteractionCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/interaction/Interaction.java
  src/main/java/seedu/address/model/person/lead/Lead.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderScheduler.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedInteraction.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#115 Improve UG
  docs/UserGuide.md
Labels: priority.High

#120 Fix Interaction reading incorrect date
  src/main/java/seedu/address/model/person/interaction/Interaction.java
Labels: type.Bug, severity.Medium

#119 Add means to stop ReminderScheduler upon exit
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reminder/ReminderScheduler.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
Labels: type.Bug, severity.Low

#118 Implement Command History
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/CommandHistoryTest.java
Labels: priority.Medium
